### ISSUE TITLE
Reporte 3 visual studio

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos-a-grupo-us#1]
[REPORTE 3 visualstudio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos-a-grupo-us/files/10788788/REPORTE.3.visualstudio.pdf)

**Comment by Nelsy21** [comment]
De acuerdo al análisis y la revisión del trabajo podemos deducir que el equipo obtuvo el 16.4 del total tomando en cuenta los criterios de la rubrica.
Buen diseño en Visual Studio, interacción en la aplicación .
Portada: 22, Usen un solo formato en la portada.
imágenes: 18, Ocupar mas capturas de pantalla, para explicar detalladamente el desarrollo de la practica, explicar paso a paso.
Procedimiento: 22, sean mas específicos en los detalles de la redacción, procurando darle un mismo formato a todo el reporte(tipo de letra, tamaño, etc.)
resultado y conclusión: 20, deben ser mas explícitos.
total=82 puntos calificación=16.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
